version: "3.2"
services:
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis-stack.conf:/redis-stack.conf
      - ./rdbs:/data
    restart: unless-stopped
    networks:
      - ournetwork

volumes:
  rdbs:
    driver: local

networks:
  ournetwork:
    name: ournetwork
    external: true
    driver: bridge
